-- 圣奥里 专用抓包悬浮窗（带过滤、带复制）
local player = game.Players.LocalPlayer

-- 1. 创建悬浮窗 UI
local gui = Instance.new("ScreenGui")
gui.Name = "MySpyGui"
gui.ResetOnSpawn = false
gui.Parent = player:WaitForChild("PlayerGui")

local mainFrame = Instance.new("Frame")
mainFrame.Size = UDim2.new(0, 450, 0, 300)
mainFrame.Position = UDim2.new(0.5, -225, 0.5, -150)
mainFrame.BackgroundColor3 = Color3.fromRGB(25, 25, 30)
mainFrame.BorderSizePixel = 2
mainFrame.BorderColor3 = Color3.fromRGB(0, 255, 100)
mainFrame.Active = true
mainFrame.Draggable = true -- 可拖动
mainFrame.Parent = gui

local titleBar = Instance.new("Frame")
titleBar.Size = UDim2.new(1, 0, 0, 35)
titleBar.BackgroundColor3 = Color3.fromRGB(40, 40, 45)
titleBar.Parent = mainFrame

local titleText = Instance.new("TextLabel")
titleText.Size = UDim2.new(1, -70, 1, 0)
titleText.Position = UDim2.new(0, 10, 0, 0)
titleText.BackgroundTransparency = 1
titleText.Text = "抓包工具 (已过滤坐标)"
titleText.TextColor3 = Color3.fromRGB(0, 255, 100)
titleText.TextSize = 18
titleText.Font = Enum.Font.GothamBold
titleText.TextXAlignment = Enum.TextXAlignment.Left
titleText.Parent = titleBar

local clearBtn = Instance.new("TextButton")
clearBtn.Size = UDim2.new(0, 50, 0, 25)
clearBtn.Position = UDim2.new(1, -60, 0, 5)
clearBtn.BackgroundColor3 = Color3.fromRGB(200, 50, 50)
clearBtn.Text = "清空"
clearBtn.TextColor3 = Color3.new(1, 1, 1)
clearBtn.TextSize = 14
clearBtn.Font = Enum.Font.GothamBold
clearBtn.Parent = titleBar

local scrollFrame = Instance.new("ScrollingFrame")
scrollFrame.Size = UDim2.new(1, -20, 1, -50)
scrollFrame.Position = UDim2.new(0, 10, 0, 45)
scrollFrame.BackgroundTransparency = 1
scrollFrame.ScrollBarThickness = 6
scrollFrame.CanvasSize = UDim2.new(0, 0, 0, 0)
scrollFrame.Parent = mainFrame

local uiList = Instance.new("UIListLayout")
uiList.Padding = UDim.new(0, 10)
uiList.Parent = scrollFrame

-- 2. 处理抓到的参数并生成可复制代码
local function formatValue(v)
    if type(v) == "string" then return string.format("%q", v) end
    if type(v) == "number" or type(v) == "boolean" then return tostring(v) end
    if typeof(v) == "Vector3" then return string.format("Vector3.new(%f, %f, %f)", v.X, v.Y, v.Z) end
    if typeof(v) == "Instance" then return "game:GetService(\""..v:GetFullName():match("^[^%.]+").."\")."..v:GetFullName():match("%.(.+)$") end
    return tostring(v)
end

local function generateCode(event, args)
    local code = "-- Script generated by R2Sv2\n"
    for i, v in ipairs(args) do
        code = code .. string.format("local A_%d = %s\n", i, formatValue(v))
    end
    code = code .. string.format("local Event = game:GetService(\"%s\")\n", event:GetFullName():match("^[^%.]+"))
    code = code .. "Event:FireServer("
    for i = 1, #args do
        if i > 1 then code = code .. ", " end
        code = code .. "A_" .. i
    end
    code = code .. ")\n"
    return code
end

-- 3. 添加抓包记录
local function addLog(event, args)
    local displayCode = generateCode(event, args)
    
    local btn = Instance.new("TextButton")
    btn.Size = UDim2.new(1, -10, 0, 60)
    btn.BackgroundColor3 = Color3.fromRGB(35, 35, 40)
    btn.TextColor3 = Color3.fromRGB(200, 200, 200)
    btn.TextSize = 13
    btn.Font = Enum.Font.Code
    btn.TextWrapped = true
    btn.Text = displayCode .. "\n\n[点击复制此段代码]"
    btn.Parent = scrollFrame
    
    btn.MouseButton1Click:Connect(function()
        if setclipboard then
            setclipboard(displayCode)
            btn.Text = "✅ 复制成功！去发给作者吧！"
            task.wait(1)
            btn.Text = displayCode .. "\n\n[点击复制此段代码]"
        else
            btn.Text = "❌ 你的执行器不支持复制，请手动截图！"
            task.wait(1)
            btn.Text = displayCode .. "\n\n[点击复制此段代码]"
        end
    end)
    
    scrollFrame.CanvasSize = UDim2.new(0, 0, 0, uiList.AbsoluteContentSize.Y + 20)
end

clearBtn.MouseButton1Click:Connect(function()
    for _, child in ipairs(scrollFrame:GetChildren()) do
        if child:IsA("TextButton") then
            child:Destroy()
        end
    end
    scrollFrame.CanvasSize = UDim2.new(0, 0, 0, 0)
end)

-- 4. 核心抓包逻辑 (过滤 charCheckpoint)
local oldNamecall
oldNamecall = hookmetamethod(game, "__namecall", function(self, ...)
    local method = getnamecallmethod()
    local args = {...}
    
    if (method == "FireServer" or method == "InvokeServer") and (self:IsA("RemoteEvent") or self:IsA("RemoteFunction")) then
        -- 过滤掉烦人的存档请求
        if args[1] ~= "charCheckpoint" and self.Name ~= "charCheckpoint" then
            addLog(self, args)
        end
    end
    
    return oldNamecall(self, ...)
end)

print("✅ 悬浮窗已加载，去黑市买东西吧！")